= CWMS 5.1 version mineure : jeudi 18 octobre 2018
:allow-uri-read: 



NOTE: Il n'y aura pas d'autres versions récurrentes pour la version 5.1 de CWMS – toutes les versions seront considérées comme des correctifs.



== CWMS 5.1 version mineure : jeudi 18 octobre 2018

Composants: 5.1 Cloud Workspace Management Suite lorsque : le jeudi 18 octobre 2018 à 22 h, à l'est : l'accès aux postes de travail Cloud Workspace et aux services applicatifs pour les utilisateurs finaux reste ininterrompu. L'accès à la suite de gestion de l'espace de travail cloud restera disponible.



=== Workspace Management Suite

* Ajouter une fonction de recherche dans la table des applications
* Tri amélioré dans la table des applications




== CWMS 5.1 version mineure : Thurs., 6 septembre 2018

Composants : suite de gestion Cloud Workspace 5.1 lorsque : jeudi 6 septembre 2018 à 22 h 00 (heure de la côte est) : l'accès aux postes de travail et aux services d'application Cloud Workspace pour les utilisateurs finaux reste ininterrompu. L'accès à la suite de gestion de l'espace de travail cloud restera disponible.



=== 5.1 Suite de gestion de l'espace de travail cloud

* Ajout de la possibilité de rechercher des sous-partenaires dans le catalogue d'applications personnalisées
* Correction d'un bug dans lequel l'actualisation de l'écran dans le module Data Centers provoque une invite d'erreur
* Suppression de la restriction sur la taille max du nom de dossier et pour faciliter la navigation dans les dossiers
* Assurez-vous que le nombre de ressources sur les machines virtuelles ne soit jamais inférieur aux valeurs minimales de CPU et de RAM spécifiées




=== 5.1 Outils et services Cloud Workspace

* Correction d'un bug avec MFA où les utilisateurs qui ont sélectionné E-mail ne recevaient pas parfois de code
* Autoriser la saisie de CPU et de RAM supplémentaires pour le type d'allocation de ressources nombre d'utilisateurs
* Correction d'un bogue pour le type d'allocation de ressources pour le type d'allocation de charge du serveur, où dans certains cas, le nombre de serveurs requis était désactivé
* Ajouter une sauvegarde lors du redémarrage automatique d'un serveur – si CwVmAutomationService est occupé, réessayez dans 20 minutes
* Amélioration de la gestion des installations de certificat générique sur CWMGR1
* Données fixes dans le rapport des ressources du centre de données
* Amélioration de la gestion de la mise à jour des ressources RAM
* Calculs améliorés sur les ressources disponibles sur le disque dur
* Introduit la prise en charge de l'API v4 de ProfitBricks, permettant le paramétrage de la famille de processeurs
* Correction de la suppression d'anciens modèles temporaires dans ProfitBricks utilisés lors de la création d'un ensemble de provisionnement
* Augmentation du délai d'attente de l'hyperviseur ProfitBricks pour créer une VM
* Lors de l'installation de nouvelles versions de VdcTools, mettez à jour VdcToolsVersionRunningAtVcc dès qu'il est en cours afin que l'automatisation s'exécute plus rapidement
* Correction d'un bogue qui serait posé lors de l'installation de certificats génériques sur les serveurs RDP Gateway
* Automatisez l'installation manuelle précédente d'un certificat générique sur le serveur FTP
* Correction d'un bug dans lequel les avis d'expiration de mot de passe n'obligaient pas les utilisateurs à mettre à jour leur mot de passe
* Amélioration du processus d'audit de fichier pour réduire la fréquence de l'erreur utilisateur inconnu qui s'affiche
* Correction d'un bogue dans lequel le rapport d'audit de fichier n'excluait pas correctement les dossiers
* Ajout d'une fonctionnalité pour installer le certificat générique si le certificat du courtier de connexion a expiré
* Correction d'un bug dans lequel les avis d'expiration de mot de passe n'apparaissent pas si le raccourci de notification d'expiration de mot de passe est supprimé du dossier de démarrage (il sera réinstallé)
* Correction d'un bug dans lequel le certificat générique n'a pas retardé une mise à jour sur les serveurs du portail HTML5 si un utilisateur était connecté
* Correction d'un bug dans lequel le certificat générique doit indiquer que des serveurs de portail HTML5 de mise à jour sont déjà à jour
* Correction d'un bug détecté lors de l'installation de certificats génériques sur les serveurs de courtier de connexion
* Résolution d'un problème de clonage où les comptes VM locaux ont été supprimés
* Résolution du problème lorsque les serveurs de clonage placent le locataire en mode migration
* Résolution d'une erreur lors du clonage de machines virtuelles dans vCloud où l'hyperviseur prenait trop de temps que prévu pour créer la machine virtuelle
* Correction d'un bug où la suppression d'une VM dans AzureRM ferait également toujours supprimer les disques gérés associés
* Résolution d'un problème de synchronisation rare lors de la création de VM dans AzureRM pour empêcher le chevauchement de deux opérations de construction
* Mise à jour de la liste des tailles et types de machines dans AzureRM
* Erreur lors de la configuration du sous-réseau dans l'hyperviseur pour GCP lors du déploiement
* Correction d'une erreur lors du stockage des données de surveillance : intégrité de la plate-forme en supprimant un délai d'écriture des données lorsqu'un serveur est occupé
* Ajout d'une fonctionnalité permettant à chaque serveur d'avoir son fuseau horaire défini individuellement ou non contrôlé par l'automatisation de la plate-forme
* Résolution d'un bug lors de la création de VM sur un site secondaire renverra des adresses IP statiques à partir du site primaire
* Correction d'une erreur lors de la capture du nom d'utilisateur pour le rapport de connexion utilisateur
* Correction d'un bogue qui n'a pas pu supprimer les anciennes données de surveillance en faisant l'appel asynchrone de sorte qu'il ne s'en serait pas sorti
* Installez automatiquement des certificats génériques sur tous les serveurs d'infrastructure




== Publication mineure de CWMS 5.1 : Thurs., 12 juillet 2018

Composants: 5.1 CWMS Tools and Services quand : jeudi 12 juillet 2018 30 à 10 h 10 (heure de l'est) impact : l'accès aux postes de travail Cloud Workspace et aux services d'application pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CWMS

* Corriger un problème concernant la persistance des paramètres du catalogue d'applications global




== Publication mineure de CWMS 5.1 : Thurs., 17 mai 2018

Composants: 5.1 Outils et services CWMS quand: Jeudi 17 mai 2018 @ 10-11 h impact est: L'accès aux bureaux Cloud Workspace et aux services d'application pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CWMS

* Résolution d'un problème concernant les résumés des utilisateurs pour les groupes App Services
* Résolution d'un problème avec l'assistant Data Center préremplissage du nom d'utilisateur et du mot de passe
* Ajoutez la validation des nom d'utilisateur pour les administrateurs VM locaux et les techniciens de niveau 3 dans l'assistant Data Center
* Amélioration de la gestion des sessions, y compris la déconnexion automatique des utilisateurs après un délai de session
* Corriger un problème lors de la suppression d'administrateurs si un administrateur principal n'a pas pu être détecté
* Modifiez le paramètre fictif dans Data Center -> le serveur de profil passe de entrer le nom du profil à entrer le profil et modifiez le libellé du nom du profil à Nom du serveur
* Résolution l'activation d'AD admin ne fonctionne pas pour les utilisateurs non Cloud Workspace
* Corriger l'erreur JavaScript empêchant l'ajout de nouveaux utilisateurs/groupes pour un client non Cloud Workspace
* Autoriser les partenaires principaux à créer des administrateurs d'utilisateurs Active Directory pour les sous-partenaires
* Corriger le bug entraînant la réinitialisation du mot de passe de l'administrateur principal d'un sous-partenaire




== SCF 5.1 diffusion mineure : mercredi 21 février 2018

Composants: 5.1 Outils et services CW quand: Wedr., fév 21, 2018 @ 10-11 h HNE impact : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CW

* Corriger le problème de gestion des dossiers utilisateur via le rôle accès administrateur




=== 5.1 Outils et services CW

* Assurez-vous que le serveur défaillant n'est pas automatiquement supprimé lors de la mise à niveau d'un client "aucun service" avec un espace de travail
* Traitez les mises à jour des GPO W2016 pour empêcher que la fenêtre contextuelle de notification ne soit brièvement visible par les utilisateurs connectés à leurs sessions RDS sur les machines virtuelles W2016




=== 5.1 API REST

* Ajouter de nouveaux attributs (modifier le rapport SPLA du SCF pour consommer de nouveaux attributs) afin de mieux gérer les applications de base basées sur des licences (plus précisément, SQL)




== SCF 5.1 diffusion mineure : mercredi 7 février 2018

Composants: 5.1 Outils et services CW quand: Wedr., fév 7, 2018 @ 10-11 h HNE impact : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CW

* Aucune




=== 5.1 Outils et services CW

* Résolution du problème de désactivation d'App Locker sur Windows 2016 (en raison d'un problème interne récemment découvert sur Windows 2016)
* Corrigez le bogue lorsque l'IP n'est pas correctement réattribué en fonction de l'événement de défaillance du clone




=== 5.1 API REST

* Correction de l'enregistrement du type de stockage lors de la modification d'un serveur dans une collection de provisionnement
* Lors de la création d'une collection de provisionnement avec deux serveurs terminal Server (TS), un seul serveur TS doit être conçu pour valider la collection




== SCF 5.1 version mineure : mercredi 31 février 2018

Composants : 5.1 Outils et services CW lorsque : mercredi, janvier 31, 2018 @ 10-11 h HNE impact : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CW

* Augmenter le nombre de rangées par tableau sur les modules CWS de haut niveau de 10 à 20
* Résolution de l'assistance utilisateur seul l'administrateur ne peut pas plonger dans un client




=== 5.1 Outils et services CW

* Corrigez le bug lorsque le modèle ne contient pas .Net Framework v4.5.2, la création du serveur échoue de manière incorrecte
* Correction du problème lors du clonage de machines virtuelles dans Hyper-V.




== SCF 5.1 version mineure : mercredi 10 février 2018

Composants : 5.1 Outils et services CW lorsque : mercredi, janvier 10, 2018 @ 10-11 h HNE impact : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 Outils et services CW

Les outils et services CWS version 5.1 (y compris le service d'automatisation CW, le service d'automatisation VM et le service CWAgent) seront mis à jour pour éliminer toute erreur d'autorisation qui se produit pour des scénarios de distribution d'application RemoteApp spécifiques. Les services seront notamment modifiés comme suit :

* Modifiez le déploiement automatique du certificat générique SSL pour les serveurs de session en le déployant uniquement sur les serveurs de serveur de connexion RD (Remote Desktop Connection Broker) et les serveurs d'utilisateurs intensifs. Les serveurs de session non-Broker utiliseront le certificat par défaut généré par les services RDS (Remote Desktop Services).
* Modifiez la zone de recherche directe DNS externe sur Active Directory au SDDC pour créer un seul enregistrement DNS pour les serveurs de sessions partagées client. Cet enregistrement pointe vers le serveur RDS Broker (VM) du client, qui gère à son tour l'équilibrage de charge entre les serveurs de session partagés. Les serveurs d'utilisateurs de puissance continueront d'avoir des entrées DNS distinctes.


Remarque : seules les configurations de clients finaux utilisant plusieurs serveurs de sessions partagées ont été affectées par ce problème, mais les configurations de clients nouveaux et modifiées seront déployées à l'aide de cette configuration.



== SCF 5.1 version mineure : mercredi 3 février 2018

Composants: 5.1 CW Web App quand: Wedr., janv 3, 2018 @ 10-10:30 HNE impact : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CW

* Corriger le tri par code de société dans le module espaces de travail CWS
* Corriger les utilisateurs de Cloud Workspace -> forcer la réinitialisation du mot de passe ne reflète pas les modifications (lorsque vous naviguez vers un autre module, puis revenez à l'utilisateur)
* Assistant de déploiement automatique SDDC : ajoutez une alerte de confirmation modale en cas de non-vérification de l'installation ThinPrint (section Licensing)




== SCF 5.1 libération mineure : Tues., Dec 5 février 2017

Composants: 5.1 CW Web App quand: Tues., Dec 5, 2017 @ 10-10:30 HNE impact : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CW

* Correction de l'erreur MFA CWS Admin sur Internet Explorer (IE) 11
* Correction des groupes CWS -> accès au lecteur local en renvoyant « non trouvé »
* Assistant d'auto-déploiement de Data Center : ajoutez la prise en charge d'AzureRM (ARM) Azure Active Directory
* Catalogue d'applications : assurez-vous que l'option d'abonnement est toujours disponible/propagé
* CWS script Events module > script Activity -> Add application : correction du chemin d'icône d'application incorrect
* Améliorez l'efficacité de la demande d'accès administrateur pour éviter les erreurs lors de la redirection vers CWS v5.0
* Corriger diverses erreurs lors de la mise à jour des détails d'AppService et/ou de la gestion des licences d'application pour un AppService
* Module d'espace de travail CWS > Assistant Ajout d'espace de travail -> fixer le format incorrect des services d'appel envoyé au plan de contrôle global
* CWS Workspace module > Assistant Ajout d'espace de travail -> Nouveau client -> Etape 3, fixer le groupe de mise à jour pour corriger l'erreur JavaScript afin de s'assurer que la mise à jour est traitée




== CWS 5.1 libération mineure : Sam., nov 11 février 2017

Composants: 5.1 CW Web App quand: Samedi, novembre 11, 2017 @ 10-11pm impact est : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu.



=== 5.1 application web CW

* À partir de 22h HNE le novembre 11, tous les partenaires du SCF 5.1 doivent utiliser https://iit.hostwindow.net[]. Cette URL est mise à niveau pour soutenir CWS 5.1 (ainsi que CWS 5.0). Les partenaires sont chargés de s'assurer que l'administrateur du SCF et les utilisateurs finaux qui ont accès aux administrateurs du SCF sont au courant de ce changement.




== SCF 5.1 version mineure : lundi., oct 30 février 2017

Composants : 5.1 CW Web App et 5.1 CW Tools & Services quand : lundi, oct 30, 2017 @ 10-11pm impact est : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu



=== 5.1 application web CW

* CWS Admin MFA : appuyez sur la touche entrée code de soumission pour MFA et corrigez le bogue, ce qui empêche le renvoi du code MFA
* Assistant d'auto-déploiement SDDC : pour GCP, demandez à l'administrateur d'utiliser un nom de VM local plutôt que de simplement être désactivé
* Assistant d'auto-déploiement SDDC : augmentez la largeur de la liste déroulante pour les fuseaux horaires
* Événements avec script : ajoutez le champ arguments à l'activité de script
* Événements avec script : ajoutez %applicationname% comme variable d'exécution pour les scripts d'événements avec script




=== 5.1 Outils et services CW

* Adresse e-mail de l'utilisateur final : résolvez le problème avec les adresses e-mail qui ne sont pas enregistrées dans la base de données pour les utilisateurs finaux existants
* État de connexion de l'utilisateur final : correction du problème d'obtention de l'UPN de l'utilisateur final connecté
* État de connexion de l'utilisateur final dans AzureRM : prend en charge les disques gérés Azure
* Modèles : corriger le flux de travail lorsque les modèles ne sont pas correctement supprimés
* Ressources : correction du problème de conversion des anciens pools de ressources en nouveaux types d'allocation
* Rapport d'audit de fichier : corrigez le bogue qui fait que l'utilisateur est inconnu
* Windows 2016 : correctif pour s'assurer que GPO à supprimer les icônes PowerShell des espaces de travail des utilisateurs finaux est correctement appliqué
* Modifier le rapport d'allocation des ressources/ressources : erreur de correction affichée de façon incorrecte
* Rapport sur les ressources du centre de données : si l'hyperviseur n'est pas configuré pour renvoyer l'espace disque dur disponible ou le devis VM, empêchez le rapport d'afficher l'erreur
* Redémarrage mensuel du serveur d'infrastructure : scénario d'adresse lorsque les serveurs d'infrastructure ne redémarrent pas chaque mois comme prévu car ils ne pouvaient pas communiquer avec le serveur CWMGR1 en raison du redémarrage de ce serveur en cours




== 5.1 version mineure : Tues., oct 3 février 2017

Composants : 5.1 CW Web App et 5.1 CW Tools & Services quand : Tues., oct 3, 2017 @ 10-11pm impact est : l'accès aux bureaux et aux services d'application Cloud Workspace pour les utilisateurs finaux restera ininterrompu



=== 5.1 application web CW

* AppServices : correction du blocage des incidents Ajout de licences pour les applications AppService
* AppServices : assurez-vous que la fonctionnalité "Ajouter une nouvelle instance" est toujours disponible pour les applications AppService
* Terminologie du pool de ressources : mettez à jour la terminologie tout en autorisant toujours l'application de la configuration du pool de ressources aux serveurs, même en l'absence de modifications : « mettre à jour » devient « appliquer aux serveurs » et « Modifier » a été remplacé par « gérer ».
* Calendrier de la charge de travail : assurez-vous que Modifier le modal s'ouvre toujours
* Calendrier des charges de travail : assurez-vous que les flèches de sélection de l'heure s'affichent toujours
* Evénements avec script : permet une sélection plus granulaire du temps
* Rapport CWS 'accès administrateur' : correction du problème entraînant la liste de plusieurs adresses IP de la colonne IP au lieu de l'adresse IP du client




=== 5.1 Outils et services CW

* Service d'audit des fichiers : désormais désactivé de manière cohérente
* Service d'automatisation et nouveau certificat générique SSL (connexions RDP) : ordre de mise à jour des commandes pour garantir que le certificat RDP mis à jour sur la passerelle RDS est toujours actualisé (c'est-à-dire non mis en cache)




== Présentation de la version initiale du CWS® 5.1

Cloud Workspace Suite 5.1 est actuellement en version bêta publique à partir du troisième trimestre 2017. Cette version inclut une mise à jour des API CWS et de l'interface de contrôle Admin. La version est une mise à jour de CWS 5.0 (sortie Q4 2016) et n'est pas « rétrocompatible » avec les entités version 4.x.

Une fois officiellement publié au quatrième trimestre 2017, il n'y a pas de frais de mise à niveau ni de frais de mise en oeuvre pour la transition au SCF 5.1. Les mises à niveau seront effectuées par CloudJumper en coordination avec chaque partenaire et n'interrompent pas les services existants. CWS 5.1 continue de prendre en charge toutes les fonctionnalités des versions précédentes, et étend les nouvelles fonctionnalités qui améliorent l'expérience des administrateurs et des utilisateurs finaux et améliorent encore l'automatisation et l'orchestration primées introduites avec les versions précédentes de Cloud Workspace Suite.

La mise à niveau de CWS 5.1 est la plus rapide et la plus simple à ce jour en étendant et en exploitant l'architecture mise à jour et la plate-forme d'API REST introduite dans CWS 5.0. CWS 5.1 poursuit l'engagement de CloudJumper en faveur d'un environnement plus amical afin de permettre aux développeurs externes d'étendre leurs services et produits basés sur Cloud Workspace.


NOTE: Le SCF 4.x atteindra la fin de vie officielle en 12.31.2017. Les partenaires qui restent sur la plate-forme CWS 4.x ne recevront plus de soutien direct pour les déploiements 4.x et aucune mise à jour 4.x ou correction de bogues supplémentaire ne sera fournie.



=== Points forts de 5.1 :

* Prise en charge de Windows 2016 Server
* Prise en charge de l'ensemble de la pile pour Microsoft Azure Resource Manager
* Prise en charge de l'authentification unique Office 365
* MFA pour les administrateurs du Portail CWS
* Amélioration de la gestion de la collecte de provisionnement
* Automatisation et script définis par l'administrateur
* Schémas de gestion du dimensionnement des ressources




==== Prise en charge de Windows 2016 Server

* Prise en charge des versions de serveur Windows Server 2016 pour toutes les plates-formes prises en charge.
* Windows 2016 Server fournit l'expérience de bureau « Windows 10 » pour les utilisateurs de sessions RDS partagées et permet des options de configuration telles que l'affectation de GPU pour les applications graphiques intensives*.




==== Prise en charge de l'ensemble de la pile pour Microsoft Azure Resource Manager

* Microsoft nécessite une migration du modèle de licence d'utilisateur pour la clé de chiffrement classique/compte délégué vers le modèle Azure Resource Manager.
* Microsoft Azure Resource Manager est une structure qui permet aux utilisateurs de travailler avec les ressources d'une solution en tant que groupe.
* Les attributs d'authentification requis sont collectés une fois lors du déploiement du data Center Software-defined (SDDC), puis réutilisés pour d'autres activités Microsoft Azure sans avoir à recourir à une nouvelle saisie ou à une nouvelle authentification.




==== Prise en charge de l'authentification unique Office 365

* Microsoft Office 365 utilise un modèle d'authentification qui exige que les utilisateurs finaux saisissent des informations d'identification chaque fois qu'ils utilisent la suite bureautique sur un nouvel ordinateur ou un nouveau périphérique.
* CWS 5.1 gère ces informations d'identification à l'échelle de la batterie de serveurs de sorte que les utilisateurs finaux n'ont besoin d'une authentification que lors de leur première utilisation d'un nouvel abonnement Office 365.




==== Une meilleure gestion de la collecte de provisionnement

* La configuration et la gestion des modèles d'hyperviseur pour des charges de travail prédéfinies peuvent être complexes, notamment lorsqu'elles sont réparties sur plusieurs plateformes d'hyperviseurs.
* CWS 5.1 introduit des fonctions de gestion automatisée de l'hyperviseur qui incluent la création d'instances de serveur basées sur un modèle existant ou une image VM de fournisseur de services cloud, une connexion directe au serveur créé pour l'installation d'applications à partir de CWS Web App; La création automatique de modèles/sysprep Windows à partir de l'instance de serveur configurée, ainsi que la validation des chemins d'accès aux applications et l'installation depuis CWS afin d'éliminer le besoin d'accéder directement au tableau de bord de l'hyperviseur ou du service cloud.




==== MFA pour les administrateurs du portail CWS

* CWS 5.1 comprend une solution d'authentification multifacteur (MFA) intégrée pour les administrateurs CWS uniquement
* Les partenaires peuvent implémenter leur propre solution MFA pour les utilisateurs finaux. Parmi les options les plus populaires, citons Duo, Auth-Anvil et Azure MF. CloudJumper publiera son propre MFA intégré pour les utilisateurs finaux au premier trimestre 2018




==== Automatisation définie par l'administrateur

* CWS assure une automatisation améliorée du déploiement et de la gestion pour les fournisseurs de services grâce à l'automatisation des tâches/l'exécution des scripts définie par l'administrateur.
* Grâce à cette amélioration, CWS 5.1 accélère considérablement les déploiements, simplifie la gestion et réduit les frais généraux.
* L'automatisation définie par l'administrateur CWS permettra d'installer ou de mettre à niveau des applications en fonction des événements, ce qui permet aux partenaires de déclencher des installations ou des opérations de maintenance automatisées à l'aide de cette méthode.




==== Schémas de gestion du dimensionnement des ressources

* La fonctionnalité des ressources du SCF 5.1 améliore la capacité de faire évoluer les ressources de façon dynamique en ajoutant trois schémas de ressources supplémentaires
* Les schémas Total Users existants sont désormais complétés par trois schémas de dimensionnement de ressources supplémentaires : fixes, actifs basés sur l'utilisateur et l'activité
* Exemple : la méthode fixe prend en charge les spécifications exactes de la CPU et de la RAM.
* Tous les schémas de dimensionnement des ressources continuent de permettre une modification immédiate/forcée ou une vérification/modification automatique nocturne des ressources.

