= Ajouter une activité manuelle
:allow-uri-read: 




=== Ajouter une activité manuelle

Pour qu'un script dans le référentiel puisse effectuer une action, une activité doit être créée pour associer ce script à un déclencheur sélectionné. Dans cet exemple, l'activité s'exécute lorsque l'administrateur VDS déclenche manuellement le script.

Les événements utilisant des scripts VDS offrent de nombreux autres types de déclencheurs d'activité tels que _Create Server_ qui pourraient être utilisés comme alternative au type d'événement _Manual_. L'utilisation de _Create Server_ doit simplement exécuter ce script sur toutes les machines virtuelles nouvellement créées dans VDS. _Create Server_ et d'autres déclencheurs sont documentés et peuvent être explorés link:Management.Scripted_Events.scripted_events.html["ici"].

.Pour créer une activité et lier ce script à une action :
. Accédez à la section événements avec script dans VDS
. Sous _Activities_, cliquez sur _+ Ajouter une activité_
. Dans la fenêtre de dialogue ouverte, entrez les informations suivantes :
+
** *Nom:* nommez cette activité
** *Description:* saisissez éventuellement une description
** *Déploiement* sélectionnez le déploiement souhaité dans la liste déroulante
** *Script:* sélectionnez le script d'installation (ou de désinstallation) dans la liste déroulante. Il peut s'agir du script global ou du script client que vous avez cloné et personnalisé.
** *Arguments:* laisser vide
** *Case à cocher activée:* `Check` la boîte
** *Type d'événement:* sélectionnez `Manual` dans la liste déroulante
** *Type de cible :* sélectionnez le `Servers` bouton radio
** *Serveurs gérés:* `Check` La boîte pour chaque machine virtuelle qui devrait recevoir cette désinstallation.



